######################################################################
##
## Filename: dma_state_machine.udo
## Created on: Thu Mar 08 10:04:11 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
