######################################################################
##
## Filename: tb_a1_complement_adder.udo
## Created on: Wed Mar 07 8:30:23 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
