######################################################################
##
## Filename: tb_dma_fsm_testing.udo
## Created on: Sat Mar 10 1:03:24 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
