######################################################################
##
## Filename: tb_dma.udo
## Created on: Thu Mar 08 15:38:49 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
