######################################################################
##
## Filename: tb_dma_test.udo
## Created on: Sat Mar 10 21:22:02 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
