######################################################################
##
## Filename: tb_dma_state_machine.udo
## Created on: Wed Mar 07 12:20:25 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
