######################################################################
##
## Filename: tb_ram_2mib.udo
## Created on: Fri Mar 02 12:04:14 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
