######################################################################
##
## Filename: tb_ram.udo
## Created on: Sat Mar 03 13:36:51 Hora estándar romance 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
